### ISSUE TITLE
Placing a shutter facing down crashes the game

### ISSUE THREAD

**Issue by ProxyLogout** [nudelauflauch/shutter#10]
I accidentally placed a shutter on the ground and it crashed my game because the block state facing down (and probably up) is not allowed.

```
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{shutter:acacia_shutter}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130) ~[client-intermediary.jar:?]
	at net.stehschnitzel.shutter.block.Shutter.method_9605(Shutter.java:160) ~[shutter-2.0.2-fabric-1.20.4.jar:?]
	
	[...]
```

**Comment by nudelauflauch** [comment]
This bug should be fixed in the newest update [shutter-2.0.4 ](https://www.curseforge.com/minecraft/mc-mods/lauchs-shutters/files/5187405)
